Spring:
  profiles: dev

server:
  port: 80
management:
  port: 54001
  security:
    enabled: false
  health:
    mail:
      enabled: false
spring:
  application:
    name: admin-managee
  freemarker:
    request-context-attribute: request
    cache: false
    suffix: .ftl

  profiles:
    active: test




debug: true

mybatis:
  typeAliasesPackage: cds.com.demo.webapp.model
  mapper-locations: classpath:cds/com/demo/webapp/dao/*.xml

info:
  aaa:
    name: xxx
    email: xxx@qq.com
  bbb:
    age: 25
    hobbies: running
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"



