server:
  port: 8080
  #上下文
  context-path: /cdstest

#服务端口
spring:
  application:
    name: springbootdemo
  freemarker:
    request-context-attribute: request
    cache: false
    suffix: .ftl

  datasource:
     url: jdbc:mysql://127.0.0.1/cds?useUnicode=true&amp;characterEncoding=UTF-8
     username: cds
     password: cds@123456
     driver_class_namel: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource

     # 初始化大小，最小，最大
     initial-size: 5
     min-idle: 5
     max-active: 20
     # 配置获取连接等待超时的时间
     max-wait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     time-between-eviction-runs-millis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     min-evictable-idle-time-millis: 300000
     # 验证查询语句
     validationQuery: SELECT 1 FROM DUAL
     test-while-idle: true
     test-on-borrow: false
     test-on-return: false
     # 打开PSCache，并且指定每个连接上PSCache的大小
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     filters: stat,wall,log4j
     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 合并多个DruidDataSource的监控数据
     useGlobalDataSourceStat: true

debug: true

#mybatis配置
mybatis:
  typeAliasesPackage: cds.com.demo.webapp.model
  mapper-locations: classpath:cds/com/demo/webapp/dao/*.xml




#健康检查  http://[ip:port]/[context-path]/info
#如        http://127.0.0.1:8080/cdstest/info
info:
  aaa:
    name: xxx
    email: xxx@qq.com
  bbb:
    age: 25
    hobbies: running
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"



